export const tools = [
  {
    id: 1,
    name: "ChatGPT",
    url: "https://chat.openai.com",
    category: "text",
    categoryText: "文本生成",
    description:
      "强大的语言模型，能够理解和生成自然语言，用于对话、写作、翻译等多种场景。",
    rating: "4.9",
    icon: "fa-comment-dots",
    badgeClass: 'bg-green-100 text-green-800',
    gradientClass: "from-primary to-secondary",
  },
  {
    id: 2,
    name: "DALL·E 3",
    url: "https://openai.com/dall-e-3",
    category: "image",
    categoryText: "图像生成",
    description:
      "OpenAI开发的图像生成模型，能够根据文本描述创建逼真的图像和艺术作品。",
    rating: "4.8",
    icon: "fa-paintbrush",
    badgeClass: 'bg-green-100 text-green-800',
    gradientClass: "from-accent to-purple-500",
  },
  {
    id: 3,
    name: "Midjourney",
    url: "https://www.midjourney.com",
    category: "image",
    categoryText: "图像生成",
    description:
      "先进的AI图像生成器，专注于创建高质量的艺术作品、概念设计和创意图像。",
    rating: "4.9",
    image: "https://picsum.photos/seed/midjourney/200/200",
    badgeClass: 'bg-green-100 text-green-800',
    gradientClass: "from-green-400 to-teal-500",
  },
  {
    id: 4,
    name: "豆包",
    url: "https://www.doubao.com",
    category: "assistant",
    categoryText: "智能助手",
    description:
      "由字节跳动开发的AI助手，提供多模态交互能力，支持文本、图像和语音处理。",
    rating: "4.9",
    icon: "fa-computer",
    gradientClass: "from-orange-500 to-red-500",
    badgeClass: "bg-orange-100 text-orange-800",
  },
  {
    id: 5,
    name: "通义千问",
    url: "https://tongyi.aliyun.com",
    category: "assistant",
    categoryText: "文本生成",
    description:
      "阿里云推出的大型语言模型，支持多轮对话、文本创作、知识问答等多种场景。",
    rating: "4.7",
    icon: "fa-robot",
    gradientClass: "from-blue-500 to-indigo-600",
    badgeClass: "bg-blue-100 text-blue-800",
  },
  {
    id: 6,
    name: "文心一言",
    url: "https://yiyan.baidu.com",
    category: "text",
    categoryText: "文本生成",
    description:
      "百度开发的大型语言模型，提供对话、文本创作、知识问答等多种AI服务。",
    rating: "4.6",
    icon: "fa-brain",
    gradientClass: "from-purple-500 to-indigo-600",
    badgeClass: "bg-purple-100 text-purple-800",
  },
  {
    id: 7,
    name: "讯飞星火",
    url: "https://xinghuo.xfyun.cn",
    category: "text",
    categoryText: "文本生成",
    description:
      "科大讯飞推出的认知智能大模型，具有跨领域知识理解和生成能力。",
    rating: "4.7",
    icon: "fa-comment",
    gradientClass: "from-teal-500 to-cyan-600",
    badgeClass: "bg-teal-100 text-teal-800",
  },
  {
    id: 8,
    name: "阿里通义万相",
    url: "https://tongyi.aliyun.com/model/dashscope/qwen-vl",
    category: "image",
    categoryText: "图像生成",
    description:
      "阿里云推出的多模态大模型，支持图像生成、编辑和理解等多种功能。",
    rating: "4.8",
    icon: "fa-image",
    gradientClass: "from-amber-500 to-orange-600",
    badgeClass: "bg-amber-100 text-amber-800",
  },
  {
    id: 9,
    name: "Claude 3",
    url: "https://anthropic.com/claude",
    category: "text",
    categoryText: "文本生成",
    description: "Anthropic最新AI模型，支持超长文本处理和多模态交互，擅长复杂推理任务",
    rating: "4.9",
    icon: "fa-lightbulb",
    badgeClass: 'bg-violet-100 text-violet-800',
    gradientClass: "from-violet-500 to-purple-600"
  },
  {
    id: 10,
    name: "Gemini",
    url: "https://gemini.google.com",
    category: "text",
    categoryText: "文本生成",
    description: "Google开发的多模态AI模型，支持文本、图像、音频和视频的综合理解与生成",
    rating: "4.8",
    icon: "fa-google",
    badgeClass: 'bg-blue-100 text-blue-800',
    gradientClass: "from-blue-500 to-cyan-600"
  },
  {
    id: 11,
    name: "Kimi AI",
    url: "https://kimi.moonshot.cn",
    category: "text",
    categoryText: "文本生成",
    description: "国产长文本处理专家，支持100万字文档解析和多轮对话，中文理解能力出色",
    rating: "4.8",
    icon: "fa-file-text",
    badgeClass: 'bg-indigo-100 text-indigo-800',
    gradientClass: "from-indigo-500 to-purple-500"
  },
  {
    id: 12,
    name: "Perplexity",
    url: "https://www.perplexity.ai",
    category: "text",
    categoryText: "文本生成",
    description: "AI驱动的搜索引擎，结合实时数据与深度分析，提供准确的答案和来源引用",
    rating: "4.7",
    icon: "fa-search",
    badgeClass: 'bg-amber-100 text-amber-800',
    gradientClass: "from-amber-500 to-orange-500"
  },
  {
    id: 13,
    name: "Cursor",
    url: "https://www.cursor.com",
    category: "code",
    categoryText: "代码辅助",
    description: "基于GPT-4的AI代码编辑器，支持实时代码生成、解释和重构，提升开发效率",
    rating: "4.9",
    icon: "fa-code",
    badgeClass: 'bg-gray-100 text-gray-800',
    gradientClass: "from-gray-700 to-blue-600"
  },
  {
    id: 14,
    name: "GitHub Copilot",
    url: "https://github.com/features/copilot",
    category: "code",
    categoryText: "代码辅助",
    description: "AI结对编程助手，支持多种编程语言，实时提供代码建议和自动补全",
    rating: "4.8",
    icon: "fa-github",
    badgeClass: 'bg-gray-100 text-gray-800',
    gradientClass: "from-gray-800 to-gray-900"
  },
  {
    id: 15,
    name: "Codeium",
    url: "https://codeium.com",
    category: "code",
    categoryText: "代码辅助",
    description: "开源AI代码补全工具，支持40+编程语言，本地部署保护代码隐私",
    rating: "4.7",
    icon: "fa-code-fork",
    badgeClass: 'bg-gray-100 text-gray-800',
    gradientClass: "from-blue-600 to-green-500"
  },
  {
    id: 16,
    name: "Runway",
    url: "https://runwayml.com",
    category: "video",
    categoryText: "视频生成",
    description: "AI视频创作平台，支持文本生成视频、智能剪辑、背景去除等专业功能",
    rating: "4.8",
    icon: "fa-film",
    badgeClass: 'bg-pink-100 text-pink-800',
    gradientClass: "from-pink-500 to-purple-600"
  },
  {
    id: 17,
    name: "Pika 1.0",
    url: "https://pika.art",
    category: "video",
    categoryText: "视频生成",
    description: "文本生成高质量视频的AI工具，支持多种风格转换和镜头控制",
    rating: "4.7",
    icon: "fa-video",
    badgeClass: 'bg-pink-100 text-pink-800',
    gradientClass: "from-purple-500 to-pink-500"
  },
  {
    id: 18,
    name: "Sora",
    url: "https://openai.com/sora",
    category: "video",
    categoryText: "视频生成",
    description: "OpenAI开发的文本到视频模型，能生成超逼真的物理世界模拟视频",
    rating: "4.9",
    icon: "fa-film",
    badgeClass: 'bg-pink-100 text-pink-800',
    gradientClass: "from-blue-500 to-indigo-600"
  },
  {
    id: 19,
    name: "Descript",
    url: "https://www.descript.com",
    category: "video",
    categoryText: "视频生成",
    description: "音频驱动的视频编辑工具，支持文字修改音频、AI配音和多轨编辑",
    rating: "4.7",
    icon: "fa-microphone",
    badgeClass: 'bg-pink-100 text-pink-800',
    gradientClass: "from-indigo-500 to-purple-500"
  },
  {
    id: 20,
    name: "Stable Diffusion",
    url: "https://stability.ai/stable-diffusion",
    category: "image",
    categoryText: "图像生成",
    description: "开源图像生成模型，支持本地部署和高度自定义，适合专业创作者",
    rating: "4.8",
    image: "https://picsum.photos/seed/stable/200/200",
    badgeClass: 'bg-rose-100 text-rose-800',
    gradientClass: "from-rose-500 to-pink-500"
  },
  {
    id: 21,
    name: "Leonardo AI",
    url: "https://leonardo.ai",
    category: "image",
    categoryText: "图像生成",
    description: "专注于游戏资产和概念设计的AI图像平台，支持3D模型生成",
    rating: "4.7",
    image: "https://picsum.photos/seed/leonardo/200/200",
    badgeClass: 'bg-amber-100 text-amber-800',
    gradientClass: "from-amber-500 to-orange-500"
  },
  {
    id: 22,
    name: "Firefly",
    url: "https://www.adobe.com/sensei/generative-ai/firefly.html",
    category: "image",
    categoryText: "图像生成",
    description: "Adobe官方AI创作工具，与PS、AI等软件无缝集成，支持商业使用",
    rating: "4.8",
    icon: "fa-paint-brush",
    badgeClass: 'bg-red-100 text-red-800',
    gradientClass: "from-red-500 to-orange-500"
  },
  {
    id: 23,
    name: "Pixso",
    url: "https://www.pixso.net",
    category: "design",
    categoryText: "设计工具",
    description: "AI驱动的在线UI/UX设计平台，支持智能组件生成和团队协作",
    rating: "4.7",
    icon: "fa-pencil-square-o",
    badgeClass: 'bg-blue-100 text-blue-800',
    gradientClass: "from-blue-500 to-cyan-500"
  },
  {
    id: 24,
    name: "Murf AI",
    url: "https://murf.ai",
    category: "audio",
    categoryText: "音频处理",
    description: "AI语音生成平台，提供超逼真的文本转语音服务和语音克隆功能",
    rating: "4.8",
    icon: "fa-microphone",
    badgeClass: 'bg-green-100 text-green-800',
    gradientClass: "from-green-500 to-teal-500"
  },
  {
    id: 25,
    name: "LALAL.AI",
    url: "https://www.lalal.ai",
    category: "audio",
    categoryText: "音频处理",
    description: "AI音频分离工具，精准提取人声、乐器和伴奏，支持多轨处理",
    rating: "4.7",
    icon: "fa-music",
    badgeClass: 'bg-purple-100 text-purple-800',
    gradientClass: "from-purple-500 to-indigo-500"
  },
  {
    id: 26,
    name: "ElevenLabs",
    url: "https://elevenlabs.io",
    category: "audio",
    categoryText: "音频处理",
    description: "高质量语音合成平台，支持200+语言和方言，情感语音生成",
    rating: "4.8",
    icon: "fa-volume-up",
    badgeClass: 'bg-amber-100 text-amber-800',
    gradientClass: "from-amber-500 to-red-500"
  },
  {
    id: 27,
    name: "Jasper",
    url: "https://www.jasper.ai",
    category: "text",
    categoryText: "文本生成",
    description: "AI内容创作平台，专注于营销文案、广告创意和SEO优化内容生成",
    rating: "4.7",
    icon: "fa-file-text-o",
    badgeClass: 'bg-green-100 text-green-800',
    gradientClass: "from-green-500 to-emerald-500"
  },
  {
    id: 28,
    name: "Copy.ai",
    url: "https://www.copy.ai",
    category: "text",
    categoryText: "文本生成",
    description: "AI驱动的文案生成工具，支持社交媒体、广告和电子邮件内容创作",
    rating: "4.6",
    icon: "fa-pencil",
    badgeClass: 'bg-blue-100 text-blue-800',
    gradientClass: "from-blue-500 to-indigo-500"
  },
  {
    id: 29,
    name: "QuillBot",
    url: "https://quillbot.com",
    category: "text",
    categoryText: "文本生成",
    description: "AI文本改写工具，支持语法检查、风格调整和学术写作辅助",
    rating: "4.7",
    icon: "fa-exchange",
    badgeClass: 'bg-purple-100 text-purple-800',
    gradientClass: "from-purple-500 to-pink-500"
  },
  {
    id: 30,
    name: "Grammarly",
    url: "https://www.grammarly.com",
    category: "text",
    categoryText: "文本生成",
    description: "AI语法检查和写作辅助工具，支持多平台集成和专业校对",
    rating: "4.8",
    icon: "fa-check-circle",
    badgeClass: 'bg-red-100 text-red-800',
    gradientClass: "from-red-500 to-pink-500"
  },
  {
    id: 31,
    name: "Kaedim",
    url: "https://www.kaedim.com",
    category: "3d",
    categoryText: "3D生成",
    description: "AI图像转3D模型工具，支持快速创建游戏资产和AR/VR内容",
    rating: "4.7",
    image: "https://picsum.photos/seed/kaedim/200/200",
    badgeClass: 'bg-cyan-100 text-cyan-800',
    gradientClass: "from-cyan-500 to-blue-500"
  },
  {
    id: 32,
    name: "Luma AI",
    url: "https://lumalabs.ai",
    category: "3d",
    categoryText: "3D生成",
    description: "手机拍摄生成3D模型和动画，支持实时渲染和AR预览",
    rating: "4.8",
    image: "https://picsum.photos/seed/luma/200/200",
    badgeClass: 'bg-indigo-100 text-indigo-800',
    gradientClass: "from-indigo-500 to-purple-500"
  },
  {
    id: 33,
    name: "HeyGen",
    url: "https://www.heygen.com",
    category: "video",
    categoryText: "视频生成",
    description: "AI数字人视频平台，支持文本生成真人讲解视频和多语言配音",
    rating: "4.7",
    icon: "fa-user-circle",
    badgeClass: 'bg-amber-100 text-amber-800',
    gradientClass: "from-amber-500 to-yellow-500"
  },
  {
    id: 34,
    name: "Canva AI",
    url: "https://www.canva.com/ai",
    category: "design",
    categoryText: "设计工具",
    description: "集成AI功能的在线设计平台，支持智能模板生成和图像编辑",
    rating: "4.8",
    icon: "fa-paint-brush",
    badgeClass: 'bg-pink-100 text-pink-800',
    gradientClass: "from-pink-500 to-purple-500"
  },
  {
    id: 35,
    name: "Notion AI",
    url: "https://www.notion.so/ai",
    category: "productivity",
    categoryText: "生产力工具",
    description: "集成AI的笔记软件，支持内容生成、摘要和智能编辑",
    rating: "4.7",
    icon: "fa-sticky-note",
    badgeClass: 'bg-gray-100 text-gray-800',
    gradientClass: "from-gray-500 to-blue-500"
  },
  {
    id: 36,
    name: "Zapier AI",
    url: "https://zapier.com/ai",
    category: "productivity",
    categoryText: "生产力工具",
    description: "AI自动化工作流平台，连接2000+应用实现无代码自动化",
    rating: "4.8",
    icon: "fa-random",
    badgeClass: 'bg-blue-100 text-blue-800',
    gradientClass: "from-blue-500 to-teal-500"
  },
  {
    id: 37,
    name: "Monica",
    url: "https://monica.im",
    category: "text",
    categoryText: "文本生成",
    description: "AI助手浏览器插件，支持实时翻译、摘要和多轮对话",
    rating: "4.6",
    icon: "fa-comments",
    badgeClass: 'bg-green-100 text-green-800',
    gradientClass: "from-green-500 to-blue-500"
  },
  {
    id: 38,
    name: "腾讯文档AI",
    url: "https://docs.qq.com/ai",
    category: "productivity",
    categoryText: "生产力工具",
    description: "集成AI功能的在线文档，支持内容生成、表格分析和思维导图",
    rating: "4.7",
    icon: "fa-file-text",
    badgeClass: 'bg-blue-100 text-blue-800',
    gradientClass: "from-blue-500 to-cyan-500"
  },
  {
    id: 39,
    name: "Windsurf",
    url: "https://codeium.com/windsurf",
    category: "code",
    categoryText: "代码辅助",
    description: "由Codeium开发的AI代码编辑器，深度集成AI技术，提供强大的AI智能代理功能，Cascade模式可自动处理复杂编码任务。",
    rating: "4.7",
    icon: "fa-code",
    badgeClass: 'bg-gray-100 text-gray-800',
    gradientClass: "from-gray-700 to-blue-600"
  },
  {
    id: 40,
    name: "Zed",
    url: "https://zed.dev/",
    category: "code",
    categoryText: "代码辅助",
    description: "一款新兴的AI代码编辑器，以直观的用户界面和强大的AI辅助功能受到欢迎。",
    rating: "4.6",
    icon: "fa-code",
    badgeClass: 'bg-gray-100 text-gray-800',
    gradientClass: "from-gray-800 to-gray-900"
  },
  {
    id: 41,
    name: "MarsCode",
    url: "https://www.marscode.cn/",
    category: "code",
    categoryText: "代码辅助",
    description: "字节跳动推出的AI代码编辑器，结合先进的自然语言处理技术和代码生成算法。",
    rating: "4.8",
    icon: "fa-code",
    badgeClass: 'bg-gray-100 text-gray-800',
    gradientClass: "from-blue-600 to-green-500"
  },
  {
    id: 42,
    name: "Pear AI",
    url: "https://trypear.ai/",
    category: "code",
    categoryText: "代码辅助",
    description: "专注于提供AI辅助编程服务的编辑器。",
    rating: "4.7",
    icon: "fa-code",
    badgeClass: 'bg-gray-100 text-gray-800',
    gradientClass: "from-gray-700 to-blue-600"
  },
  {
    id: 43,
    name: "Surfer Writesonic",
    url: "https://www.surfer.com/",
    category: "text",
    categoryText: "文本生成",
    description: "专为社交媒体内容打造的AI文案工具，可快速生成吸引人的标题和广告文案。",
    rating: "4.6",
    icon: "fa-file-text-o",
    badgeClass: 'bg-green-100 text-green-800',
    gradientClass: "from-green-500 to-emerald-500"
  },
  {
    id: 44,
    name: "Rytr",
    url: "https://rytr.me/",
    category: "text",
    categoryText: "文本生成",
    description: "提供个性化内容建议的AI文案工具，让每篇文案更贴近读者需求。",
    rating: "4.7",
    icon: "fa-pencil",
    badgeClass: 'bg-blue-100 text-blue-800',
    gradientClass: "from-blue-500 to-indigo-500"
  },
  {
    id: 45,
    name: "Jasper",
    url: "https://www.jasper.ai/",
    category: "text",
    categoryText: "文本生成",
    description: "可优化长篇文章，提升SEO排名，增强在线可见性的AI文案工具。",
    rating: "4.7",
    icon: "fa-file-text-o",
    badgeClass: 'bg-green-100 text-green-800',
    gradientClass: "from-green-500 to-emerald-500"
  },
  {
    id: 46,
    name: "Duolingo",
    url: "https://www.duolingo.com/",
    category: "language",
    categoryText: "语言学习",
    description: "结合游戏化学习，通过智能适应技术为不同水平学习者定制个性化学习路径的AI英语学习工具。",
    rating: "4.8",
    icon: "fa-graduation-cap",
    badgeClass: 'bg-yellow-100 text-yellow-800',
    gradientClass: "from-yellow-500 to-orange-500"
  },
  {
    id: 47,
    name: "Pronounce",
    url: "https://www.pronounceapp.com/",
    category: "language",
    categoryText: "语言学习",
    description: "通过AI技术提供发音练习和即时反馈，有效提升口语表达能力的AI英语学习工具。",
    rating: "4.7",
    icon: "fa-microphone",
    badgeClass: 'bg-green-100 text-green-800',
    gradientClass: "from-green-500 to-teal-500"
  },
  {
    id: 48,
    name: "Lingvist",
    url: "https://www.lingvist.com/",
    category: "language",
    categoryText: "语言学习",
    description: "利用智能算法优化词汇学习，帮助用户高效记忆英语单词的AI英语学习工具。",
    rating: "4.7",
    icon: "fa-book",
    badgeClass: 'bg-blue-100 text-blue-800',
    gradientClass: "from-blue-500 to-cyan-500"
  },
  {
    id: 49,
    name: "ELSA Speak",
    url: "https://elsaspeak.com/",
    category: "language",
    categoryText: "语言学习",
    description: "专注于英语发音训练，通过AI分析提供个性化的发音改进建议的AI英语学习工具。",
    rating: "4.8",
    icon: "fa-microphone",
    badgeClass: 'bg-amber-100 text-amber-800',
    gradientClass: "from-amber-500 to-red-500"
  },
];
